[package]
name = "validator-utils"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.7.4"
gw-types = { git = "https://github.com/thewawar/godwoken.git", rev = "01acfac841e7ce136ada251e941903cd7dcfcfca", default-features = false }
gw-common = { git = "https://github.com/thewawar/godwoken.git", rev = "01acfac841e7ce136ada251e941903cd7dcfcfca", default-features = false }
